#pragma once

#include <stdint.h>

#include "PacketHeader.h"
#include "PacketID.h"

constexpr uint16_t IOCP_ENGINE_PROTOCOL_VERSION = 1;

enum class SYSTEM_AUTH_RESULT : uint16_t
{
	SUCCESS = 0,
	FAILED = 1,
	INVALID_STATE = 2,
	PROTOCOL_MISMATCH = 3,
};

#pragma pack(push, 1)

struct CS_SYSTEM_AUTH_REQUEST_PACKET
{
	PACKET_HEADER header = PACKET_HEADER(PACKET_ID::CS_SYSTEM_AUTH_REQUEST, sizeof(CS_SYSTEM_AUTH_REQUEST_PACKET));
	uint16_t protocolVersion = IOCP_ENGINE_PROTOCOL_VERSION;

	CS_SYSTEM_AUTH_REQUEST_PACKET() = default;
};

struct SC_SYSTEM_AUTH_RESPONSE_PACKET
{
	PACKET_HEADER header = PACKET_HEADER(PACKET_ID::SC_SYSTEM_AUTH_RESPONSE, sizeof(SC_SYSTEM_AUTH_RESPONSE_PACKET));
	uint16_t authResult = static_cast<uint16_t>(SYSTEM_AUTH_RESULT::SUCCESS);
	uint16_t protocolVersion = IOCP_ENGINE_PROTOCOL_VERSION;

	SC_SYSTEM_AUTH_RESPONSE_PACKET() = default;
};

struct SC_SYSTEM_HEARTBEAT_REQUEST_PACKET
{
	PACKET_HEADER header = PACKET_HEADER(PACKET_ID::SC_SYSTEM_HEARTBEAT_REQUEST, sizeof(SC_SYSTEM_HEARTBEAT_REQUEST_PACKET));
	uint64_t tick = 0;

	SC_SYSTEM_HEARTBEAT_REQUEST_PACKET() = default;
};

struct CS_SYSTEM_HEARTBEAT_RESPONSE_PACKET
{
	PACKET_HEADER header = PACKET_HEADER(PACKET_ID::CS_SYSTEM_HEARTBEAT_RESPONSE, sizeof(CS_SYSTEM_HEARTBEAT_RESPONSE_PACKET));
	uint64_t tick = 0;

	CS_SYSTEM_HEARTBEAT_RESPONSE_PACKET() = default;
};

#pragma pack(pop)
